### ISSUE TITLE
create leiningen template for stream processing.

### ISSUE THREAD

**Issue by BrunoBonacci** [samsara/samsara#58]
To simplify the creation and development a stream processing project a leiningen template should be provided.

By default should use the latest stable release, but provided a parameter should be possible to use a specific version or the latest SNAPSHOT.

The template should provide a project file, a main, a simple processing file with only one pipeline, and a test file to test the pipeline.

here is a sample structure for an app called `my-streaming-app` which is basically a default `lein new` application with the addition of some files. The files marked as `(*)` are specific to Samsara's.

```
my-streaming-app/
├── CHANGELOG.md
├── LICENSE
├── README.md                 (*)
├── config
│   └── config.edn             (*)
├── doc
│   └── intro.md
├── docker-compose.yml   (*)
├── project.clj                      (*)
├── resources
├── src
│   └── my_streaming_app
│       ├── core.clj               (*)
│       └── main.clj              (*)
└── test
    └── my_streaming_app
        └── core_test.clj         (*)
```

## project.clj

Here is the sample content of the `project.clj`

Dynamic parts: 
  * The project name (or group/name)
  * samsara's version (default to latest) but the user should be able to specify a specific version with `--with-version=a.b.c.d` or `--with-snapshot` to use the latest snapshots

```
(defproject my-streaming-app "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"

  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}

  :dependencies [[org.clojure/clojure "1.8.0"]
                 [samsara/samsara-core "0.5.5.0"]]

  :main my-streaming-app.main

  :profiles {:uberjar {:aot :all}
             :dev {:dependencies [[midje "1.7.0"]]
                   :plugins [[lein-midje "3.1.3"]
                             [lein-binplus "0.4.1"]]}}
  )
```

## main.clj

Here is the sample content of the `main.clj`

Dynamic parts: 
  * the ns name

```
(ns my-streaming-app.main
  (:require [my-streaming-app.core :refer :all]
            [samsara-core.main :as sam])
  (:gen-class))


(defn -main [config-file]
  (println "Starting streaming processing.")
  (sam/start-processing! (sam/init! config-file)))
```

## core.clj

Here is the sample content of the `core.clj`

Dynamic parts: 
  * the ns name

```
(ns my-streaming-app.core
  (:require [samsara-core.core :as sam] ; default pipeline
            [moebius.core :refer :all]  ; processing functions
            [moebius.kv :as kv]         ; state management
            ))


;;
;; Enrichment example.
;; You can compute any additional field and inject it
;; directly into the event.
;;
(defenrich game-name
  [event]
  (assoc event :game-name "Apocalypse Now"))


;;
;; Filtering example.
;; You can tell the pipeline to discard events
;; which match a particular condition.
;;
(deffilter no-ads [{:keys [eventName]}]
  (not= eventName "game.ad.displayed"))

;;
;; Correlation example.
;; Based on the events you are processing
;; you can produce new events
;;
(defcorrelate new-player
  [{:keys [eventName level timestamp sourceId] :as event}]

  (when (and (= eventName "game.started")
             (= level 1))
    [{:timestamp timestamp :sourceId sourceId :eventName "game.new.player"}]))

;;
;; Pipelines.
;; Finally you can compose your pipelines
;; chaining your processing functions in the order
;; you wish process them.
;;
(def my-pipeline
  (pipeline
   (sam/make-samsara-pipeline {})
   game-name
   no-ads
   new-player))


;;
;; Finally you can produce a moebius
;; function which is it used by Samsara-CORE
;; to process incoming events.
;;
(defn make-processor [config]
  (moebius my-pipeline))
```

## config.edn

Here is the sample content of the `config.edn`

```
{:streams
 [{:id           :ingestion
   :input-topic  "ingestion"
   :state        :partitioned
   :output-topic "events"
   :processor    "my-streaming-app.core/make-processor"
   }]

 :job
 {:job-name "my-streaming-app"
  ;; a CSV list of hosts and ports (and optional path)
  :zookeepers "127.0.0.1:2181"
  ;; a CSV list of host and ports of kafka brokers
  :brokers "127.0.0.1:9092"
  :offset :smallest
  ;; this is useful only for local development
  :samza-overrides { :task.checkpoint.replication.factor 1 }
  }

 :tracking {:enabled true :type :console
            :reporting-frequency-seconds 600}

 }
```

## docker-compose.yaml

Here is the sample content of the `docker-compose.yaml`

Dynamic parts:

  * the version of the images like `samsara/kafka:snapshot` should be the same as the version requested with `--wtih-version`
  * the local IP address in `ADV_IP: "192.168.0.2"` should be the address of the develoment machine

```
#
# Zookeeper
#
zookeeper:
  image: samsara/zookeeper:snapshot
  ports:
    - "2181:2181"
    - "15001:15000"
  environment:
    ZK_SERVER_ID: 1
    ADV_IP: "192.168.0.2"
  volumes:
    - /tmp/logs/zk1:/logs
    - /tmp/data/zk1:/data

#
# Kafka
#
kafka:
  image: samsara/kafka:snapshot
  ports:
    - "9092:9092"
    - "15002:15000"
  links:
    - zookeeper:zookeeper
  environment:
    KAFKA_BROKER_ID: 1
    ADV_IP: "192.168.0.2"
  volumes:
    - /tmp/logs/kafka1:/logs
    - /tmp/data/kafka1:/data

#
# Samsara Ingestion API
#
ingestion:
  image: samsara/ingestion-api:snapshot
  links:
    - kafka:kafka
    - monitoring:riemann
  ports:
    - "9000:9000"
    - "15003:15000"
  environment:
    OUTPUT_TOPIC: "ingestion"
    TRACKING_ENABLED: "true"
  volumes:
    - /tmp/logs/ingestion-api:/logs

#
# Samsara CORE
#
#core:
#  image: myuser/my-streaming-app
#  links:
#    - kafka:kafka
#    - zookeeper:zookeeper
#    - monitoring:riemann
#  ports:
#    - "15010:15000"
#  environment:
#    TRACKING_ENABLED: "true"
#    SINGLE_BROKER: "true"
#  volumes:
#    - /tmp/logs/core:/logs


#
# ElasticSearch
#
elasticsearch:
  image: samsara/elasticsearch:snapshot
  links:
    - zookeeper:zookeeper
  ports:
    - "9200:9200"
    - "9300:9300"
    - "15004:15000"
  volumes:
    - /tmp/logs/els:/logs
    - /tmp/data/els:/data

#
# Kibana
#
kibana:
  image: samsara/kibana:snapshot
  links:
    - elasticsearch:elasticsearch
  ports:
    - "8000:8000"
    - "15005:15000"
  volumes:
    - /tmp/logs/kibana:/logs

#
# Samsara Qanal
#
qanal:
  image: samsara/qanal:snapshot
  links:
    - zookeeper:zookeeper
    - elasticsearch:els
    - monitoring:riemann
  ports:
    - "15006:15000"
  environment:
    TRACKING_ENABLED: "true"
    KAFKA_TOPICS_SPEC: |
      { :topic "events" :partitions :all :type :plain
        :indexing {:strategy :simple :index "events" :doc-type "events" :id-field "id"}}
  volumes:
    - /tmp/logs/qanal1:/logs

#
# Monitoring
#
monitoring:
  image: samsara/monitoring:snapshot
  ports:
    - "15000:80"
    - "5555:5555"
    - "5556:5556"
    - "8083:8083"
    - "8086:8086"
  environment:
    HTTP_USER: admin
    HTTP_PASS: samsara
  volumes:
    - /tmp/logs/monitoring:/logs
    - /tmp/data/monitoring:/data


#
# Bootstrap
#
bootstrap:
  image: samsara/kafka:snapshot
  links:
    - zookeeper:zookeeper
    - kafka:kafka
    - elasticsearch:elasticsearch
  command: bash -c "curl -sSL 'https://raw.githubusercontent.com/samsara/samsara/master/docker-images/bootstrap/bootstrap.sh' | bash"
  volumes:
    - /tmp/logs/bootstrap:/logs

```

# README.md

Here is the sample content of `README.md`

Dynamic parts:

  * app name `my-streaming-app` should be changed according to the given name

```
# my-streaming-app

A Samsara's streaming app designed to ... well, that part is up to you.

## Usage

### Build

You can build the app with:

    lein do clean, compile :all

### Test

You can test your streaming logic with:

    lein midje

You can run tests automatically while coding with:

    lein midje :autotest


### Build executable

You can build a executable jar with:

    lein do clean, bin


### Run

Start a local cluster with:

    docker-compose up

When it is up and running you can start the streaming with:

    lein do clean, bin
    ./target/my-streaming-app-0.1.0-SNAPSHOT config/config.edn

or in development run with:

    lein run config/config.edn


Finally you can send events to:

    cat <<EOF | curl -i -H "Content-Type: application/json" \
                    -H "X-Samsara-publishedTimestamp: $(date +%s999)" \
                    -XPOST "http://127.0.0.1:9000/v1/events" -d @-
    [
      {
        "timestamp": $(date +%s000),
        "sourceId": "test-device",
        "eventName": "game.started",
        "level": 1,
        "levelScore": $RANDOM
      }
    ]
    EOF

And see the events via [http://217.0.0.1:8000](http://217.0.0.1:8000).
The first time you'll need to set it up as described in [Quick start guide](http://samsara-analytics.io/docs/quick-start/).

## License

Copyright © 2016 FIXME

Distributed under the Eclipse Public License either version 1.0 or (at
your option) any later version.

```

## core_test.clj

Here is the sample content of the `core_test.clj`

Dynamic parts:

  - namespace

```
(ns my-streaming-app.core-test
  (:require [my-streaming-app.core :refer :all]
            [midje.sweet :refer :all]))


(fact "ENRICHMENT: the game-name must be injected into all events"
      (game-name
       {:eventName "game.started"
        :timestamp 1430760258401
        :sourceId "device1"
        :level 1})
      => (contains {:game-name "Apocalypse Now"}))



(fact "FILTERING: filtering should drop game.ad.displayed"

      ;; no surprise here the predicates work like in filter function
      (no-ads {:eventName "game.level.completed"
               :timestamp 1430760258403
               :sourceId "device1"
               :levelCompleted 1})
      => true

      ;; when it doesn't match `false` or `nil` is returned
      (no-ads  {:eventName "game.ad.displayed"
                :timestamp 1430760258402
                :sourceId "device1"})
      => false)



(fact "CORRELATION: when a game.started event if found with a level=1,
       we could infer that a new player started play with our game."

      (new-player {:eventName "game.started"
                   :timestamp 1430760258401
                   :sourceId "device1"
                   :level 1})
      =>
      [{:timestamp 1430760258401, :sourceId "device1", :eventName "game.new.player"}]

      (new-player {:eventName "game.started"
                   :timestamp 1430760258401
                   :sourceId "device1"
                   :level 5})
      => nil)

```
